env: "local"

http_server:
  address: "localhost:8082"
  timeout: 10s
  idle_timeout: 60s

storage:
  deck_path: "./web/data/deck.json"
  spread_path: "./web/data/spreads.json"

ai:
  mode: "cloud"
  
  # Локальный AI (Ollama)
  local:
    url: "http://localhost:11434/api/generate"
    model: "llama3"

  # Облачный AI (OpenRouter)
  cloud:
    url: "https://openrouter.ai/api/v1/chat/completions"
    model: "qwen/qwen3.6-plus:free"
